spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  pid:
    file: events-gateway.pid
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false


management:
  endpoint:
    health:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info
